/*
 * Port_PBCfg.c
 *
 *  Created on: Jan 11, 2025
 *      Author: mohamed elsharawy
 */
#include"Port.h"
const Port_ConfigType Port_Configurations={
                                     PORT_PIN_IN,PORT_PIN0,PORT_A_ID,PORT_PIN_ALT1,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_OUT,PORT_PIN1,PORT_A_ID,PORT_PIN_ALT1,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN2,PORT_A_ID,PORT_PIN_GPIO_MODE,PULL_UP_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN3,PORT_A_ID,PORT_PIN_GPIO_MODE,PULL_DOWN_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN4,PORT_A_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN5,PORT_A_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN6,PORT_A_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN7,PORT_A_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN0,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN1,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN2,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN3,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN4,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN5,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN6,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN7,PORT_B_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN0,PORT_C_ID,PORT_PIN_ALT1,PULL_UP_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN1,PORT_C_ID,PORT_PIN_ALT1,PULL_UP_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN2,PORT_C_ID,PORT_PIN_ALT1,PULL_UP_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN3,PORT_C_ID,PORT_PIN_ALT1,PULL_UP_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN4,PORT_C_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN5,PORT_C_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN6,PORT_C_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN7,PORT_C_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN0,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN1,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN2,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN3,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN4,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN5,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN6,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN7,PORT_D_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN0,PORT_E_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN1,PORT_E_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN2,PORT_E_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN3,PORT_E_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN4,PORT_E_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN5,PORT_E_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN0,PORT_F_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_OUT,PORT_PIN1,PORT_F_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN2,PORT_F_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN3,PORT_F_ID,PORT_PIN_GPIO_MODE,INTERNAL_RESISTANCE_OFF,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,

                                     PORT_PIN_IN,PORT_PIN4,PORT_F_ID,PORT_PIN_GPIO_MODE,PULL_UP_RESISTANCE,CFG_UNCHANGEABLE,CFG_UNCHANGEABLE,


};

